import assert from 'node:assert/strict';
import {Simulation} from '../lib/fabric/simulator';
import {DEFAULTS,WORKLOADS,PROFILES,ProfileId} from '../lib/fabric/catalog';
import {topology,graphStats} from '../lib/fabric/topology';
const serialization=new Simulation(DEFAULTS);serialization.heap.a=[];serialization.flows=[];serialization.addFlow(0,1,16384,0,0,'serialization check');const single=serialization.finish();assert.ok(Math.abs(single.makespan-(2*16384/(400*125)+2*.15))<1e-9,'exact two-link serialization + propagation');assert.equal(single.bytes,16384);
type TestResult={profile:ProfileId;base:number|null;peak:number}|{workload:typeof WORKLOADS[number]['id'];flows:number;us:number;p99:number}|{trouble:string;collective:number|null;bytes:number;retries:number};
const output:TestResult[]=[];
const g=graphStats(topology(DEFAULTS));assert.equal(g.components,1);assert.equal(g.switches,32);assert.equal(g.diameter,3);
for(const profile of Object.keys(PROFILES) as ProfileId[]){const c={...DEFAULTS,profile};const s=new Simulation(c),a=s.finish(),b=new Simulation(c).finish();assert.deepEqual(a,b,'Deterministic replay');assert.equal(a.censored,0);assert.equal(a.completed,128*7);assert.equal(a.bytes,128*7*c.messageKiB*1024);for(const l of s.t.links)for(const p of l.directions){assert.equal(p.bytes,0);assert.equal(p.busy,false)}output.push({profile,base:a.collective,peak:a.peakQueue});}
for(const w of WORKLOADS){const s=new Simulation({...DEFAULTS,workload:w.id,injectAt:30,repairAt:300},w.id==='onepercent');const r=s.finish();assert.ok(s.flows.length>0,w.id+' generated demand');assert.equal(r.censored,0,w.id+' drains');assert.equal(r.bytes,s.flows.reduce((a,f)=>a+f.bytes,0),w.id+' byte conservation');assert.ok(s.t.links.every(l=>l.directions.every(p=>p.bytes===0)),w.id+' empty queues');output.push({workload:w.id,flows:r.completed,us:r.makespan,p99:r.packetP99});}
for(const trouble of ['cut','switch','plane','optical','slow','incast','noise','burst']){const s=new Simulation({...DEFAULTS,workload:'allreduce',messageKiB:256,injectAt:30,repairAt:300,trouble},true);const r=s.finish(20000);assert.equal(r.censored,0,trouble+' eventual recovery');assert.equal(r.bytes,s.flows.reduce((a,f)=>a+f.bytes,0),trouble+' payload conserved');assert.ok(s.t.links.every(l=>l.directions.every(p=>p.bytes===0)),trouble+' queues drained');output.push({trouble,collective:r.collective,bytes:r.bytes,retries:r.retries});}
const baseline=new Simulation({...DEFAULTS,messageKiB:256}).finish();const impairment=new Simulation({...DEFAULTS,messageKiB:256,trouble:'optical',injectAt:30,repairAt:300},true).finish();assert.ok(impairment.collective!>=baseline.collective!,'derating delays this paired workload');
const ideal=new Simulation({...DEFAULTS,profile:'quantum',collective:true});const bound=ideal.finish();assert.equal(bound.completed,254);assert.equal(bound.censored,0);assert.equal(bound.bytes,254*DEFAULTS.messageKiB*1024);
console.log(JSON.stringify({passed:true,cases:output.length+3,output},null,2));
