export type ProfileId='slingshot'|'quantum'|'spectrum'|'ultra';
export type WorkloadId='allreduce'|'alltoall'|'mpi'|'incast'|'elephant'|'graph'|'checkpoint'|'mixed'|'exascale'|'physical'|'onepercent';
export const SOURCES=[{id:'mpi-semantics',title:'Collective completion semantics',url:'https://www.mpi-forum.org/docs/mpi-4.1/mpi41-report/node114.htm',date:'MPI 4.1 · checked 9 September 2026',note:'Collective completion is local; it does not universally synchronize all participants. The lab exposes both global and local dependency assumptions.'},
{id:'hpe400',title:'HPE Slingshot interconnect 400 · QuickSpecs',date:'Current page · checked 9 Sep 2026',url:'https://www.hpe.com/us/en/collaterals/collateral.a50002547enw.html',note:'64 × 400G; all-to-all/fat tree; packet or flow routing according to ordering; perpetrator feedback; traffic classes. NIC MPI/SHMEM acceleration is not modeled as in-switch reduction.'},
{id:'quantum',title:'NVIDIA Quantum-X800 · platform documentation',date:'Current page · checked 9 Sep 2026',url:'https://www.nvidia.com/en-us/networking/products/infiniband/quantum-x800/',note:'144 × 800G connectivity, adaptive routing, telemetry congestion control and SHARP v4. No vendor latency or speedup figures are imported.'},
{id:'spectrum6',title:'NVIDIA Spectrum-6 · platform update',date:'21 Jul 2026',url:'https://blogs.nvidia.com/blog/nvidia-spectrum-six-arrives-in-gigascale-ai-factories/',note:'Spectrum-6 102.4 Tb/s generation. Bandwidth is a hardware capability, not the capacity of this reduced graph.'},
{id:'spxpaper',title:'High-speed Networking for Giga-Scale AI Factories',date:'20 May 2026 · NVIDIA-authored preprint',url:'https://arxiv.org/abs/2605.21187',note:'Separate per-packet switch routing, endpoint congestion control and NIC plane selection. This simulator uses simplified substitutes; it does not reproduce published evaluations.'},
{id:'uec',title:'UEC · public specification history',date:'1.0.3 · 16 Jul 2026',url:'https://ultraethernet.org/specification-history/',note:'Current published revision is 1.0.3. UET is a transport specification, not a switch product or prescribed topology.'},
{id:'uecspec',title:'Ultra Ethernet specification 1.0.3',date:'16 Jul 2026 · current public specification',url:'https://ultraethernet.org/wp-content/uploads/sites/20/2026/08/UE-Specification-1.0.3.pdf',note:'UET transport, AI and HPC profiles, packet spraying, flexible delivery ordering, direct data placement, congestion management and receiver credit control.'},
{id:'uecnotes',title:'UEC 1.0.3 · release notes',date:'16 Jul 2026',url:'https://ultraethernet.org/wp-content/uploads/sites/20/2026/07/UE-Specification-1.0.3-release-notes-.pdf',note:'Corrections include connection establishment, multipath range and credit accounting; also 200 Gb/s per-lane signaling.'},
];
export const PROFILES:Record<ProfileId,{name:string;short:string;generation:string;topology:'dragonfly'|'clos'|'planes';color:string;rate:number;policy:string;documented:string;source:string[]}>={
slingshot:{name:'HPE Slingshot',short:'Slingshot',generation:'Interconnect 400',topology:'dragonfly',color:'#54e6c1',rate:400,policy:'Queue-aware minimal / nonminimal',documented:'Packet adaptation for unordered traffic; ordered flows retain a route. Fine-grained congestion feedback distinguishes injecting perpetrators from victims. Configurable traffic classes.',source:['hpe400']},
quantum:{name:'NVIDIA Quantum',short:'Quantum IB',generation:'Quantum-X800 · SHARP v4',topology:'clos',color:'#b2d880',rate:800,policy:'Adaptive equal-cost paths',documented:'Adaptive routing, telemetry-driven congestion control and SHARP in-network reduction. The optional ideal tree here is an algorithmic bound, not a SHARP implementation.',source:['quantum']},
spectrum:{name:'NVIDIA Spectrum-X',short:'Spectrum-X',generation:'Spectrum-6 · multiplane',topology:'planes',color:'#74baff',rate:800,policy:'Queue-aware plane + path selection',documented:'RoCE switch/SuperNIC coordination, packet routing, destination rate control and independent NIC plane selection. Two planes are modeled here.',source:['spectrum6','spxpaper']},
ultra:{name:'Ultra Ethernet',short:'Ultra Ethernet',generation:'UET · specification 1.0.3',topology:'clos',color:'#c4acff',rate:800,policy:'Deterministic packet spraying',documented:'Transport-based multipathing and flexible ordering; sender congestion control and optional receiver credit control. A generic Clos is an experiment choice, not a UEC-mandated architecture.',source:['uec','uecspec','uecnotes']}
};
export const WORKLOADS:{id:WorkloadId;name:string;detail:string}[]=[
{id:'allreduce',name:'All-Reduce',detail:'128 ranks · recursive doubling · 7 dependent rounds'},
{id:'alltoall',name:'All-to-All / MoE',detail:'128 ranks · pairwise exchange · phased bursts'},
{id:'mpi',name:'MPI latency',detail:'4 KiB messages · randomized peer exchanges'},
{id:'incast',name:'Synchronized incast',detail:'127 senders · one receiver · final-hop bottleneck'},
{id:'elephant',name:'Elephant + mice',detail:'Bulk transfers (32 × payload) overlap 4 KiB messages'},
{id:'graph',name:'Graph traversal',detail:'Skewed destinations · small irregular remote messages'},
{id:'checkpoint',name:'Checkpoint storm',detail:'128 ranks · four targets · 16 × payload per transfer'},
{id:'mixed',name:'Mixed tenant',detail:'Three tenants · training exchanges / MPI / checkpoints'},
{id:'exascale',name:'Synthetic exascale',detail:'Neighbor exchanges, synchronization and irregular traffic'},
{id:'physical',name:'Physical AI',detail:'Camera / LiDAR / control / model streams → inference'},
{id:'onepercent',name:'The 1% problem',detail:'All-Reduce · degrade ceil(1% of fabric links) to 10% rate'}
];
export const TROUBLES=[{id:'cut',name:'Sever a fabric link'},{id:'incast',name:'Create an incast hotspot'},{id:'noise',name:'Inject a noisy neighbor'},{id:'switch',name:'Disable a switch'},{id:'optical',name:'Degrade 1% of fabric links'},{id:'plane',name:'Isolate a plane / link domain'},{id:'slow',name:'Slow one endpoint'},{id:'burst',name:'Synchronize a microburst'}];
export type Config={profile:ProfileId;workload:WorkloadId;seed:number;load:number;messageKiB:number;adaptive:boolean;qos:boolean;receiver:boolean;collective:boolean;normalized:boolean;commonTopology:boolean;ordered:boolean;locality:number;rate:number;bufferKiB:number;feedbackUs:number;hopUs:number;computeUs:number;trouble:string;injectAt:number;repairAt:number;synchronization:'round'|'local';degradedCapacity:number};
export const DEFAULTS:Config={profile:'slingshot',workload:'allreduce',seed:7341,load:65,messageKiB:256,adaptive:true,qos:true,receiver:true,collective:false,normalized:true,commonTopology:false,ordered:false,locality:0,rate:400,bufferKiB:512,feedbackUs:4,hopUs:.15,computeUs:100,trouble:'cut',injectAt:30,repairAt:520,synchronization:'round',degradedCapacity:10};
