'use client';
import PacketTiming from './PacketTiming';
import {ArrowRight,ArrowLeft,Play,Pause,RotateCcw,Network,ScanLine,FlaskConical} from 'lucide-react';
import {Simulation,Packet} from '@/lib/fabric/simulator';
import {Config,DEFAULTS} from '@/lib/fabric/catalog';
import {TracePanel,CausalPanel,GraphPanel,num} from './Panels';
export const TOUR_CONFIG:Config={...DEFAULTS,workload:'allreduce',messageKiB:256,trouble:'optical',injectAt:30,repairAt:520};
export const CHAPTERS=[
 {label:'The machine',title:'Fast computers still have to wait.',body:'Big AI and scientific jobs are shared across many computers. To make progress together, those computers must exchange results. This lab lets you see what happens between them.',look:'The cabinets hold computers. The lines connect them. Moving lights are simulated pieces of a message.',takeaway:'The network is part of the computer.',detail:'This reduced model has 128 active participants, called ranks. The larger cabinet scene represents 2,048 conceptual endpoints; only the 128 modeled ranks generate traffic.'},
 {label:'One message',title:'Follow one small piece of the job.',body:'A message is split into packets. Each packet passes through network switches, where it may wait for a busy connection. A very fast link can still have a queue.',look:'The highlighted route is a recorded packet journey. The playhead moves through its actual simulated hop timings.',takeaway:'Travel time includes waiting time.',detail:'This is a completed, store-and-forward packet trace. Queueing, serialization and propagation are recorded separately. The replay slows that recorded journey to a readable pace; it is not a new simulation.'},
 {label:'A healthy run',title:'Everyone has to finish the round.',body:'In this experiment, 128 participants exchange results in seven rounds. The next round starts only after the slowest exchange in the current round finishes.',look:'The seven bars show the time spent in each round. This completed healthy run is our reference for the next experiment.',takeaway:'A shared job moves at the pace of its stragglers.',detail:'The workload is a recursive-doubling all-reduce abstraction: 256 KiB per rank per round, a 10 µs software gap between rounds, and 400 Gb/s normalized link rates. Values are microseconds (millionths of a second).'},
 {label:'Cause trouble',title:'One weak connection. A longer wait.',body:'Now replay exactly the same job, but reduce one busy fabric connection to a tenth of its capacity. Watch the network respond as packets seek other paths.',look:'Red marks the degraded connection. Amber columns show queued data; moving trails reveal packet direction. The comparison measures the completed job, even while this slower visual replay is still running.',takeaway:'A small affected area can delay the whole job.',detail:'At 30 µs, ceil(1% of the 76 fabric links) is derated by 90%: one link, or 1.32% of this reduced fabric. The link is chosen from traffic observed before injection. Repair is scheduled at 520 µs, after this collective completes.'},
 {label:'Show the evidence',title:'Trace the delay back to its cause.',body:'A lower-capacity connection changes where packets wait and which routes they use. Waiting messages hold up a round; that delay then carries into the shared result.',look:'This graph removes the cabinets. Blue highlights mark the five edges with highest shortest-path centrality. The evidence below comes from the completed impaired run.',takeaway:'An explanation should be backed by inspectable events.',detail:'Graph structure and traffic are different evidence. Centrality counts unweighted shortest paths; it does not predict congestion by itself. Queue records, route choices and round completion times describe what actually happened in this simulation.'},
 {label:'Your turn',title:'Now ask a better infrastructure question.',body:'Instead of asking only how fast a connection is, ask how the whole system behaves under demand and failure. You can now change the workload, routing policy or architecture and test the tradeoffs.',look:'Open the experiment to inspect this exact result, or compare four architecture abstractions using matched baseline and impaired runs.',takeaway:'Performance is a property of the whole system.',detail:'These are deterministic browser simulations, not hardware measurements or vendor rankings. Architecture profiles change topology and policy assumptions. The full lab exposes those assumptions and links to their public technical sources.'}
];
export type TourResult={baseline:ReturnType<Simulation['summary']>;impaired:ReturnType<Simulation['summary']>};
type Props={step:number;auto:boolean;progress:number;result:TourResult|null;sim:Simulation;packet:Packet|null;microTime:number;move:(n:number)=>void;play:()=>void;exit:(target?:string)=>void;restart:()=>void;method:()=>void;capture:()=>void;analyze:()=>void;selectNode:(id:number)=>void};
export default function GuidedTour(p:Props){const chapter=CHAPTERS[p.step],b=p.result?.baseline.collective,i=p.result?.impaired.collective;const delta=b&&i?(i/b-1)*100:0;
 return <>
 <section className="tour-story" aria-label="Guided walkthrough">
  <div className="tour-kicker">A 90-SECOND FIELD GUIDE <span>NO BACKGROUND NEEDED</span></div>
  <nav className="tour-chapters" aria-label="Walkthrough chapters">{CHAPTERS.map((c,n)=><button key={c.label} title={c.label} aria-label={`Chapter ${n+1}: ${c.label}`} aria-current={n===p.step?'step':undefined} className={n===p.step?'current':n<p.step?'visited':''} onClick={()=>p.move(n)}><span>{n+1}</span></button>)}</nav>
  <div className="tour-chapter-label">{String(p.step+1).padStart(2,'0')} / {chapter.label}</div>
  <h1 key={p.step}>{chapter.title}</h1><p className="tour-body">{chapter.body}</p>
  <div className="tour-look"><ScanLine size={16}/><p><b>What you’re looking at</b>{chapter.look}</p></div>
  <details className="tour-detail" key={`detail-${p.step}`} onToggle={e=>{if(e.currentTarget.open&&p.auto)p.play()}}><summary>Show technical details</summary><p>{chapter.detail}</p>{p.step===1&&<TracePanel sim={p.sim} packet={p.packet} selectPacket={p.capture} microTime={p.microTime}/>} {p.step===4&&<><CausalPanel sim={p.sim}/><GraphPanel sim={p.sim} onSelect={p.selectNode}/></>}</details>
  <div className="tour-navigation"><button className="tour-back" onClick={()=>p.move(p.step-1)} disabled={p.step===0} aria-label="Previous chapter"><ArrowLeft size={18}/></button><button className="tour-primary" onClick={()=>p.step===5?p.exit():p.move(p.step+1)}>{p.step===0?'Show me how it works':p.step===2?'Cause trouble':p.step===5?'Explore this experiment':'Next chapter'}<ArrowRight size={17}/></button></div>
  <div className="tour-play-row"><button onClick={p.play}>{p.auto?<Pause size={14}/>:<Play size={14}/>} {p.auto?'Pause walkthrough':p.step===0?'Watch automatically · 90 sec':'Continue automatically'}</button><button onClick={p.restart} aria-label="Restart walkthrough"><RotateCcw size={14}/></button></div>
  <div className="tour-progress" role="progressbar" aria-label="Walkthrough progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round((p.step+p.progress)/6*100)}><i style={{width:(p.step+p.progress)/6*100+'%'}}/></div>
 </section>
 <aside className="tour-evidence" aria-label="Experiment explained">
  <span className="eyebrow">{p.step<2?'THE ESSENTIAL IDEA':'ONE CONTROLLED EXPERIMENT'}</span><h2>{chapter.takeaway}</h2>
  {p.step===0&&<div className="tour-intro-facts"><div><strong>128</strong><span>participants working together</span></div><div><strong>1</strong><span>weak connection to investigate</span></div><p>You’ll follow a message, introduce a problem, and see the measured effect inside this model.</p></div>}
  {p.step===1&&<div className="tour-packet-facts"><Network size={24}/><strong>{p.packet?p.packet.hops.length:'…'} hops</strong><span>on this recorded route</span><div className="tour-stat"><span>Packet’s total journey</span><b>{p.packet?.done?num(p.packet.done-p.packet.born,2):'…'} µs</b></div><p>A hop is one connection between neighboring components.</p>{p.packet&&<PacketTiming packet={p.packet} time={p.microTime}/>}</div>}
  {p.step>=2&&<><div className="tour-comparison"><div><span>Healthy job</span><b>{b?num(b,1):'…'} <small>µs</small></b><i style={{width:b&&i?(b/i*100)+'%':'0%'}}/></div>{p.step>=3&&<div className="impaired"><span>With one degraded link</span><b>{i?num(i,1):'…'} <small>µs</small></b><i style={{width:i?'100%':'0%'}}/></div>}</div>{p.step>=3&&<div className="tour-impact"><strong>{b&&i?(delta>=0?'+':'')+num(delta,1)+'%':'…'}</strong><span>communication completion time<br/>in this simulated experiment</span></div>}
  {p.step===2&&<div className="tour-rounds"><span>Seven dependent rounds</span>{p.sim.collectiveRounds.map((r,n)=><div key={n}><b>{n+1}</b><i style={{width:Math.max(2,(r.end-r.start)/Math.max(1,...p.sim.collectiveRounds.map(rr=>rr.end-rr.start))*100)+'%'}}/><small>{num(r.end-r.start,1)} µs</small></div>)}</div>}
  {p.step===3&&<div className="tour-stat"><span>Visual replay</span><b>{p.sim.collectiveEnd?'Job complete':num(p.sim.time,0)+' µs'}</b></div>}
  {p.step===4&&<div className="tour-cause-facts"><div><span>Intervention</span><b>1 link → 10% capacity</b></div><div><span>Observed response</span><b>{p.result?.impaired.reroutes.toLocaleString()||'…'} alternate-path selections</b></div><div><span>Measured consequence</span><b>{b&&i?num(i-b,1):'…'} µs added to the collective</b></div></div>}
  {p.step>=2&&<button className="tour-analysis" onClick={p.analyze}><ScanLine size={16}/>Inspect rounds, ranks & traffic<ArrowRight size={14}/></button>}{p.step===5&&<div className="tour-explore-actions"><button onClick={()=>p.exit('compare')}><FlaskConical size={16}/>Compare architectures<ArrowRight size={14}/></button><button onClick={()=>p.exit('trace')}><ScanLine size={16}/>Inspect a packet<ArrowRight size={14}/></button></div>}
  <p className="tour-controls-note">Same seed, workload and settings. Only the link intervention changes.</p></>}
  <button className="tour-method" onClick={p.method}>Simulated results · inspect assumptions ↗</button>
 </aside>
 <div className="tour-scene-label"><span className="live-dot"/>{p.step===1?'RECORDED PACKET REPLAY':p.step===2?'HEALTHY RUN · COMPLETED':p.step===4?'IMPAIRED RUN · CONNECTION GRAPH':p.step===5?'EXPERIMENT COMPLETE':p.step===0?'SIMULATED MACHINE':'LIVE SIMULATED FABRIC'}<small>Drag to look around · scroll to zoom</small></div>
 </>;
}
