'use client';
import {useEffect,useRef,useState} from 'react';
import {Pause,Play,RotateCcw,ArrowUpRight,Volume2,VolumeX} from 'lucide-react';
import ScaleScene,{FilmClock} from './ScaleScene';
import evidence from '@/lib/fabric/film-recording.json';
const chapters=[
 {at:0,to:8,label:'01 / THE MACHINE',title:'A computer made of computers.',body:'128 participants share one job. The network lets them work together.',scale:'COMPUTER ROOM'},
 {at:8,to:17,label:'02 / THE CABINET',title:'Follow the connection inward.',body:'The modeled fabric has 32 switches in eight groups. These cabinets illustrate the setting, not its physical layout.',scale:'CABINET'},
 {at:17,to:28,label:'03 / THE BOARD',title:'The network has a physical heart.',body:'This representative board provides physical context. Its components and layout are illustrative, not a specific switch design.',scale:'CIRCUIT BOARD'},
 {at:28,to:38,label:'04 / THE PROCESSOR',title:'Packets are our smallest modeled unit.',body:'The simulation follows routes, queue waits, and transmission times. Transistor geometry and chip circuitry are outside its scope.',scale:'ILLUSTRATIVE SWITCH PACKAGE'},
 {at:38,to:49,label:'05 / THE BOTTLENECK',title:'A fast connection can still make you wait.',body:'Follow one recorded packet across six hops. The amber bars show its measured queue waits in the simulation.',scale:'RECORDED PACKET · SIX HOPS'},
 {at:49,to:60,label:'06 / THE EVIDENCE',title:'Now measure the effect on the whole job.',body:'The same workload, seed, and settings. Only one link changes. These completion records come from the simulator.',scale:'RECORDED PAIRED EXPERIMENT'},
 {at:60,to:72,label:'07 / THE BIG PICTURE',title:'The network is part of the computer.',body:'One degraded link extends this collective by '+evidence.delta.toFixed(1)+' microseconds. Explore why in the full lab.',scale:'BACK TO THE MACHINE'}
];
export default function ImmersiveDemo({exit}:{exit:()=>void}){
 const clock=useRef<FilmClock>({time:0,paused:false,reduced:false}),[time,setTime]=useState(0),[paused,setPaused]=useState(false),[ready,setReady]=useState(false),[details,setDetails]=useState(false),[voice,setVoice]=useState(false);
 const progress=useRef<HTMLDivElement>(null),readout=useRef<HTMLSpanElement>(null),speech=useRef(false),spoken=useRef(-1);
 const index=chapters.findIndex(c=>time<c.to),chapter=chapters[index<0?6:index];
 useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;clock.current.reduced=reduced;if(reduced){clock.current.paused=true;setPaused(true)}let last=performance.now(),next=0,raf=0;function tick(now:number){const dt=(now-last)/1000;last=now;if(ready&&!document.hidden&&!clock.current.paused){clock.current.time=Math.min(72,clock.current.time+Math.min(dt,1));if(clock.current.time>=72){clock.current.paused=true;setPaused(true)}}if(progress.current)progress.current.style.width=clock.current.time/72*100+'%';if(readout.current)readout.current.textContent=Math.floor(clock.current.time)+' / 72 sec';if(now>next){setTime(clock.current.time);next=now+150}raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[ready]);
 useEffect(()=>{if(!voice||paused||!('speechSynthesis' in window))return;const i=index<0?6:index;if(spoken.current===i)return;spoken.current=i;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(chapters[i].title+' '+chapters[i].body);u.rate=.96;window.speechSynthesis.speak(u)},[index,voice,paused]);
 useEffect(()=>()=>{if(speech.current&&'speechSynthesis' in window)window.speechSynthesis.cancel()},[]);
 function toggle(){clock.current.paused=!clock.current.paused;if(clock.current.time>=72){clock.current.time=0;clock.current.paused=false;spoken.current=-1}setPaused(clock.current.paused);if(clock.current.paused&&speech.current)window.speechSynthesis.cancel()}
 function seek(t:number){clock.current.time=t;setTime(t);spoken.current=-1;}
 const replayTime=Math.max(0,Math.min(1,(time-49)/10))*evidence.impaired;const row=evidence.timeline[Math.min(120,Math.round(replayTime/evidence.impaired*120))];
 return <main className="scale-film">
 <ScaleScene clock={clock} onReady={()=>setReady(true)}/>
 <header className="film-header"><a className="film-brand" href="#" onClick={e=>{e.preventDefault();seek(0)}}>FABRIC<span>REALITY LAB</span></a><button onClick={exit}>Open the lab <ArrowUpRight size={17}/></button></header>
 {!ready&&<div className="film-loading" role="status">Preparing the journey…</div>}
 <div className="film-scale"><span>{chapter.scale}</span><small>Illustrative hardware · not to physical scale</small></div>
 <section className="film-caption" aria-live="off"><span>{chapter.label}</span><h1>{chapter.title}</h1><p>{chapter.body}</p></section>
 {time>=38&&time<49&&<aside className="film-results film-packet" aria-label="Recorded packet queue waits"><span>PACKET {evidence.packet.id} · RANK {evidence.packet.src} → {evidence.packet.dst}</span><h2>{evidence.packet.wait.toFixed(2)} µs waiting</h2><p>Across {evidence.packet.hops.length} hops · {evidence.packet.duration.toFixed(2)} µs total</p><ol>{evidence.packet.hops.map((hop,i)=><li key={i}><span>Hop {i+1}</span><div className="hop-wait"><i style={{width:hop.wait/Math.max(...evidence.packet.hops.map(h=>h.wait))*100+'%'}}/></div><b>{hop.wait.toFixed(2)} µs</b></li>)}</ol><small>Recorded model output · bar length shows queue wait</small></aside>}
 {time>=49&&<aside className="film-results" aria-label="Recorded comparison"><span>SAME JOB / ONE CHANGE</span><div><label>Healthy <b>{evidence.healthy.toFixed(1)} µs</b></label><div className="result-track"><i style={{width:row.healthy*100+'%'}}/></div></div><div><label>Degraded link <b>{evidence.impaired.toFixed(1)} µs</b></label><div className="result-track impaired"><i style={{width:row.impaired*100+'%'}}/></div></div><p>{time<59?Math.round(replayTime)+' µs · completed exchanges':<><strong>+{evidence.percent.toFixed(1)}%</strong> communication time</>}</p><button onClick={()=>{setDetails(!details);clock.current.paused=true;setPaused(true)}} aria-expanded={details}>Inspect the evidence</button></aside>}
 {details&&<aside className="film-evidence"><button onClick={()=>setDetails(false)}>Close evidence</button><h2>Recorded, not estimated.</h2><p>The reduced model runs a seven-round all-reduce with 128 ranks. At 30 µs, one of 76 fabric links is derated to 10% capacity. Repair is scheduled after completion.</p><p>Packet {evidence.packet.id} from rank {evidence.packet.src} to {evidence.packet.dst} took <b>{evidence.packet.duration.toFixed(2)} µs</b>, including <b>{evidence.packet.wait.toFixed(2)} µs queued</b> over {evidence.packet.hops.length} hops.</p><p>The hardware geometry is illustrative; it does not reconstruct a vendor board or transistor layout. The paired completion figures and packet timings are recorded simulator output, not hardware or vendor benchmarks.</p><button onClick={exit}>Inspect the full simulation <ArrowUpRight size={16}/></button></aside>}
 <footer className="film-controls"><div className="film-control-row"><button aria-label={paused?'Play film':'Pause film'} onClick={toggle}>{paused?<Play size={18}/>:<Pause size={18}/>}<span>{time>=72?'Replay':paused?'Play':'Pause'}</span></button><button aria-label="Restart film" onClick={()=>{seek(0);clock.current.paused=false;setPaused(false)}}><RotateCcw size={17}/></button><span ref={readout} className="film-time">0 / 72 sec</span><button className="film-voice" aria-pressed={voice} onClick={()=>{if(!('speechSynthesis' in window))return;setVoice(!voice);speech.current=!voice;spoken.current=-1;if(voice)window.speechSynthesis.cancel()}}>{voice?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{voice?'Voice on':'Read aloud'}</span></button></div><label className="film-timeline"><span className="sr-only">Film position</span><div className="film-progress"><div ref={progress}/></div><input aria-label="Film position" type="range" min="0" max="72" step="0.1" value={time} onChange={e=>{seek(Number(e.target.value));clock.current.paused=true;setPaused(true)}}/></label><div className="film-markers">{chapters.map((c,i)=><button key={c.at} onClick={()=>seek(c.at)} aria-label={`Jump to ${c.scale.toLowerCase()}`} style={{left:c.at/72*100+'%'}} aria-current={chapter===c?'step':undefined}>{['ROOM','CABINET','BOARD','PACKAGE','PACKET','COMPARISON','SYSTEM'][i]}</button>)}</div></footer>
 </main>;
}
