'use client';
import {useState,useEffect,useRef} from 'react';
import {Simulation,percentile,finishAsync} from '@/lib/fabric/simulator';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {num,bytes} from './Panels';
type SynchronizationResult=ReturnType<Simulation['summary']>&{synchronization:'round'|'local'};
export default function RunAnalysis({sim,inspect}:{sim:Simulation;inspect:(rank:number)=>void}){
 const [tab,setTab]=useState(sim.collectiveRounds.length?'rounds':'traffic'),[round,setRound]=useState(Math.max(0,sim.collectiveRounds.length-1)),[rank,setRank]=useState<number|null>(null),[pair,setPair]=useState<[number,number]|null>(null),[bench,setBench]=useState<SynchronizationResult[]|null>(null),[busy,setBusy]=useState(false);
 const cancelled=useRef(false);useEffect(()=>{cancelled.current=false;return()=>{cancelled.current=true}},[]);
 const flows=sim.flows.filter(f=>f.end>0),r=sim.collectiveRounds[round],rf=flows.filter(f=>f.round===round),last=rf.reduce((a,f)=>!a||f.end>a.end?f:a,null as typeof rf[number]|null),cutoff=r?.end||sim.time;
 const selected=rf.find(f=>f.dst===rank),global=sim.c.synchronization!=='local'||sim.ideal;
 const matrix=Array.from({length:8},()=>Array(8).fill(0));for(const f of sim.flows)matrix[Math.floor(f.src/16)][Math.floor(f.dst/16)]+=f.received;
 const tailMax=Math.max(1,...flows.map(f=>f.latency));
 const matrixMax=Math.max(1,...matrix.flat()),filtered=pair?flows.filter(f=>Math.floor(f.src/16)===pair[0]&&Math.floor(f.dst/16)===pair[1]):flows;
 const runBench=async()=>{setBusy(true);setBench(null);const out=[];try{for(const synchronization of ['round','local'] as const){const result=await finishAsync(new Simulation({...sim.c,synchronization,collective:false},false),4000,()=>cancelled.current);if(!result)return;out.push({synchronization,...result})}if(!cancelled.current)setBench(out)}finally{if(!cancelled.current)setBusy(false)}};
 return <div className="run-analysis"><span className="eyebrow">RECORDED RUN · SEED {sim.c.seed} · {num(sim.time,1)} µs</span><h2>See where the time went.</h2><p>Inspect the actual message completions and delivered bytes behind the scene. Click a round, a participant, or a traffic cell to drill down.</p>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="analysis-tabs"><TabsTrigger value="rounds">Round timeline</TabsTrigger><TabsTrigger value="traffic">Traffic matrix</TabsTrigger><TabsTrigger value="tails">Latency tails</TabsTrigger></TabsList></Tabs>
 {tab==='rounds'&&(sim.collectiveRounds.length?<>
 <div className="analysis-layout"><section><h3>Rounds can reveal hidden waiting</h3><p className="analysis-note">{global?'This run uses a global barrier between rounds. Teal is the round’s elapsed communication time.':'This run advances each rank after its own send and receive complete. Rounds may overlap.'}</p><div className="round-waterfall">{sim.collectiveRounds.map((rr,n)=><button key={n} className={n===round?'selected':''} onClick={()=>{setRound(n);setRank(null)}} aria-pressed={n===round}><span>Round {n+1}</span><div><i style={{left:rr.start/Math.max(1,sim.collectiveEnd||sim.time)*100+'%',width:Math.max(.3,((rr.end||sim.time)-rr.start)/Math.max(1,sim.collectiveEnd||sim.time)*100)+'%'}}/></div><b>{rr.end?num(rr.end-rr.start,1)+' µs':'in flight'}</b></button>)}</div><div className="analysis-axis"><span>0</span><span>{num(sim.collectiveEnd||sim.time,1)} µs · common time axis</span></div></section>
 <section className="round-facts"><span className="eyebrow">ROUND {round+1}</span><h3>{last?`${r?.end?'Last arrival':'Latest completed arrival'}: rank ${last.dst}${rf.filter(f=>Math.abs(f.end-last.end)<1e-8).length>1?' (tied)':''}`:'Messages still in flight'}</h3><strong>{last?num(last.end-(r?.start||0),2):'—'} <small>µs</small></strong><p>{global?'Every earlier arrival waits until the round ends.':'Completion spread does not mean every participant was stalled; this run has local dependencies.'}</p><div className="kv"><span>Arrived messages</span><b>{rf.length} / {sim.flows.filter(f=>f.round===round).length}</b></div><div className="kv"><span>{global?'Mean round-end wait':'Mean completion spread'}</span><b>{num(rf.reduce((s,f)=>s+Math.max(0,cutoff-f.end),0)/Math.max(1,rf.length),2)} µs</b></div></section></div>
 <div className="rank-title"><h3>{global?'Who waited for the last arrival?':'How far apart did the arrivals finish?'}</h3><span>Amber = longer {global?'wait':'spread'} · outline = last arrival</span></div><div className="rank-grid">{Array.from({length:128},(_,id)=>{const f=rf.find(f=>f.dst===id),wait=f?Math.max(0,cutoff-f.end):0;const alpha=f?.15+Math.min(.8,wait/Math.max(1,cutoff-(r?.start||0))*.8):0;return <button key={id} className={`${f&&last&&Math.abs(f.end-last.end)<1e-8?'last-arrival':''} ${id===rank?'chosen':''}`} style={{background:f?`rgba(244,181,106,${alpha})`:'#152833'}} onClick={()=>setRank(id)} aria-label={`Rank ${id}: ${f?num(wait,2)+' microseconds '+(global?'wait':'spread'):'not completed'}`} title={`Rank ${id}: ${f?num(wait,2)+' µs':'not completed'}`}>{id}</button>})}</div>
 <div className="rank-selection" aria-live="polite">{rank===null?'Select any participant to inspect its arrival.':selected?<><span>Rank {rank}: received from {selected.src} at <b>{num(selected.end,2)} µs</b>; {global?'wait':'spread'} <b>{num(Math.max(0,cutoff-selected.end),2)} µs</b>.</span><button className="secondary" onClick={()=>inspect(rank)}>Inspect rank {rank} in 3D</button></>:<span>Rank {rank} has no completed incoming message in this round.</span>}</div>
 <div className="sync-experiment"><div><h3>Does the synchronization assumption matter?</h3><p>Compare healthy runs with global rounds and per-rank send/receive dependencies. Same workload and seed; no fault and no ideal reduction tree.</p></div><button className="secondary" disabled={busy} onClick={runBench}>{busy?'Running both policies…':'Test both synchronization policies'}</button></div>{bench&&<div className="sync-results">{bench.map(b=><div key={b.synchronization}><span>{b.synchronization==='round'?'Global round barriers':'Local rank dependencies'}</span><b>{b.collective?num(b.collective,2)+' µs':'Not complete by horizon'}</b><small>{b.completed} completed flows · {b.censored} incomplete</small></div>)}</div>}
 </>:<div className="analysis-empty"><h3>This workload has independent messages.</h3><p>Use Traffic matrix and Latency tails to inspect it, or choose an All-Reduce workload for dependent rounds.</p><button className="secondary" onClick={()=>setTab('traffic')}>Inspect traffic</button></div>)}
 {tab==='traffic'&&<div className="analysis-layout"><section><h3>Who is sending to whom?</h3><p className="analysis-note">Rows are source groups; columns are destination groups. Each cell sums delivered payload bytes. Brighter cells carried more data; this is not link utilization.</p><div className="traffic-grid"><span/>{Array.from({length:8},(_,n)=><span key={n}>To G{n}</span>)}{matrix.map((row,src)=><div className="traffic-row" key={src}><span>G{src} →</span>{row.map((value:number,dst:number)=><button key={dst} aria-label={`Group ${src} to group ${dst}: ${bytes(value)}`} aria-pressed={pair?.[0]===src&&pair?.[1]===dst} onClick={()=>setPair([src,dst])} style={{background:`rgba(107,223,194,${.05+value/matrixMax*.85})`,color:value/matrixMax>.45?'#061b19':'#bcdbda'}} title={bytes(value)}>{value?num(value/1048576,1):'·'}</button>)}</div>)}</div><small className="analysis-note">Cells display MiB. Diagonal cells connect ranks in the same group of 16; their routes can still leave that group.</small></section><section><h3>{pair?`G${pair[0]} → G${pair[1]}`:'All groups'}</h3><p>{pair?bytes(matrix[pair[0]][pair[1]]):bytes(sim.bytesDelivered)} delivered. Select a traffic cell to see its slowest completed messages.</p><button className="secondary" onClick={()=>setPair(null)} disabled={!pair}>Show all groups</button><div className="analysis-flows">{[...filtered].sort((a,b)=>b.latency-a.latency).slice(0,6).map(f=><button key={f.id} onClick={()=>inspect(f.src)}><span>Rank {f.src} → {f.dst}<small>{f.kind}</small></span><b>{num(f.latency,2)} µs</b></button>)}</div></section></div>}
 {tab==='tails'&&<><h3>Averages can hide the slowest messages</h3><p className="analysis-note">Flow completion latency includes the entire message, measured from its scheduled start. These completed-flow histograms share the same latency axis; bar heights are scaled within each class. Unfinished flows are listed separately.</p><div className="tail-cards">{[{name:'All messages',a:flows},{name:'Latency class',a:flows.filter(f=>f.cls===1)},{name:'Bulk class',a:flows.filter(f=>f.cls===0)}].map(group=>{const a=group.a.map(f=>f.latency),max=tailMax,hist=Array(12).fill(0);a.forEach(v=>hist[Math.min(11,Math.floor(v/max*12))]++);return <section key={group.name}><h3>{group.name}</h3><span>{a.length} completed</span><div className="histogram" role="img" aria-label={`${group.name}: ${a.length} samples${a.length?'; p99 '+num(percentile(a,.99),2)+' microseconds':'; no completed messages'}`}>{hist.map((v,n)=><i key={n} title={`${v} flows · ${num(n*max/12,2)}–${num((n+1)*max/12,2)} µs`} style={{height:Math.max(1,v/Math.max(1,...hist)*100)+'%'}}/>)}</div><div className="analysis-axis"><span>0</span><span>{a.length?num(max,1):'—'} µs</span></div>{[.5,.95,.99].map(q=><div className="kv" key={q}><span>p{q*100}</span><b>{a.length?num(percentile(a,q),2)+' µs':'No samples'}</b></div>)}</section>})}</div><p className="analysis-note">{sim.flows.filter(f=>!f.end).length} launched flows are incomplete at {num(sim.time,1)} µs.{!sim.collectiveEnd&&sim.collectiveRounds.length?' Later dependent rounds may not have launched yet.':''}</p></>}
 <p className="analysis-footnote">A reduced store-and-forward model. Global barriers are an explicit assumption, not a requirement of every collective implementation. Local dependencies model completion of each rank’s own send and receive; no compute overlap, memory transport or proprietary control law is emulated.</p>
 </div>
}
